name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install make
      run: sudo make install
    - name: make all
      run:  make all -C Food_order/3_Implementation/make 
 
